/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio/index'
import { Route as PortfolioContentRouteImport } from './routes/portfolio/content'
import { Route as PortfolioManageRouteImport } from './routes/portfolio/manage'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as PostsSlugRouteImport } from './routes/posts/$slug'
import { Route as PostsNewRouteImport } from './routes/posts/new'
import { Route as PortfolioWorksIndexRouteImport } from './routes/portfolio/works/index'
import { Route as PortfolioWorksIdRouteImport } from './routes/portfolio/works/$id'
import { Route as PortfolioWorksNewRouteImport } from './routes/portfolio/works/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioContentRoute = PortfolioContentRouteImport.update({
  id: '/portfolio/content',
  path: '/portfolio/content',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioManageRoute = PortfolioManageRouteImport.update({
  id: '/portfolio/manage',
  path: '/portfolio/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsNewRoute = PostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioWorksIndexRoute = PortfolioWorksIndexRouteImport.update({
  id: '/portfolio/works/',
  path: '/portfolio/works/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioWorksIdRoute = PortfolioWorksIdRouteImport.update({
  id: '/portfolio/works/$id',
  path: '/portfolio/works/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioWorksNewRoute = PortfolioWorksNewRouteImport.update({
  id: '/portfolio/works/new',
  path: '/portfolio/works/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portfolio/content': typeof PortfolioContentRoute
  '/portfolio/manage': typeof PortfolioManageRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts/new': typeof PostsNewRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/portfolio/works/$id': typeof PortfolioWorksIdRoute
  '/portfolio/works/new': typeof PortfolioWorksNewRoute
  '/portfolio/works/': typeof PortfolioWorksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portfolio/content': typeof PortfolioContentRoute
  '/portfolio/manage': typeof PortfolioManageRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts/new': typeof PostsNewRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/posts': typeof PostsIndexRoute
  '/portfolio/works/$id': typeof PortfolioWorksIdRoute
  '/portfolio/works/new': typeof PortfolioWorksNewRoute
  '/portfolio/works': typeof PortfolioWorksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portfolio/content': typeof PortfolioContentRoute
  '/portfolio/manage': typeof PortfolioManageRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts/new': typeof PostsNewRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/portfolio/works/$id': typeof PortfolioWorksIdRoute
  '/portfolio/works/new': typeof PortfolioWorksNewRoute
  '/portfolio/works/': typeof PortfolioWorksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/portfolio/content'
    | '/portfolio/manage'
    | '/posts/$slug'
    | '/posts/new'
    | '/portfolio/'
    | '/posts/'
    | '/portfolio/works/$id'
    | '/portfolio/works/new'
    | '/portfolio/works/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/portfolio/content'
    | '/portfolio/manage'
    | '/posts/$slug'
    | '/posts/new'
    | '/portfolio'
    | '/posts'
    | '/portfolio/works/$id'
    | '/portfolio/works/new'
    | '/portfolio/works'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/portfolio/content'
    | '/portfolio/manage'
    | '/posts/$slug'
    | '/posts/new'
    | '/portfolio/'
    | '/posts/'
    | '/portfolio/works/$id'
    | '/portfolio/works/new'
    | '/portfolio/works/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PortfolioContentRoute: typeof PortfolioContentRoute
  PortfolioManageRoute: typeof PortfolioManageRoute
  PostsSlugRoute: typeof PostsSlugRoute
  PostsNewRoute: typeof PostsNewRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
  PortfolioWorksIdRoute: typeof PortfolioWorksIdRoute
  PortfolioWorksNewRoute: typeof PortfolioWorksNewRoute
  PortfolioWorksIndexRoute: typeof PortfolioWorksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/content': {
      id: '/portfolio/content'
      path: '/portfolio/content'
      fullPath: '/portfolio/content'
      preLoaderRoute: typeof PortfolioContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/manage': {
      id: '/portfolio/manage'
      path: '/portfolio/manage'
      fullPath: '/portfolio/manage'
      preLoaderRoute: typeof PortfolioManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/new': {
      id: '/posts/new'
      path: '/posts/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof PostsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/works/': {
      id: '/portfolio/works/'
      path: '/portfolio/works'
      fullPath: '/portfolio/works/'
      preLoaderRoute: typeof PortfolioWorksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/works/$id': {
      id: '/portfolio/works/$id'
      path: '/portfolio/works/$id'
      fullPath: '/portfolio/works/$id'
      preLoaderRoute: typeof PortfolioWorksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/works/new': {
      id: '/portfolio/works/new'
      path: '/portfolio/works/new'
      fullPath: '/portfolio/works/new'
      preLoaderRoute: typeof PortfolioWorksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PortfolioContentRoute: PortfolioContentRoute,
  PortfolioManageRoute: PortfolioManageRoute,
  PostsSlugRoute: PostsSlugRoute,
  PostsNewRoute: PostsNewRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
  PortfolioWorksIdRoute: PortfolioWorksIdRoute,
  PortfolioWorksNewRoute: PortfolioWorksNewRoute,
  PortfolioWorksIndexRoute: PortfolioWorksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
